server:
  port: 8081

spring:
  security:
    basic:
      enabled: false
    user:
      name: user
      password: 123456
  application:
    name: demo
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/user?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&autoReconnect=true
    username: root
    password: mttop123@
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialSize: 5
    min-idle: 5
    max-active: 20
    max-wait-millis: 60000
    min-evictable-idle-time-millis: 3000000
    validation-query: SELECT 1 FROM DUAL
    test-while-idle: true
    test-on-borrow: false
    druid:
      exceptionSorter: true
      filters: stat,wall
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
    useGlobalDataSourceStat: true

# 健康检查
management:
  endpoints:
    web:
      exposure:
        include: "*"
  server:
    port: 8082
    servlet:
      context-path: /
    ssl:
      enabled: false
  endpoint:
    health:
      show-details: always